export const TaroifyIcons = [
  {
    title: "基础图标",
    icons: {
      Arrow: "Arrow",
      ArrowLeft: "ArrowLeft",
      ArrowUp: "ArrowUp",
      ArrowDown: "ArrowDown",
      Success: "Success",
      Cross: "Cross",
      Plus: "Plus",
      Minus: "Minus",
      Fail: "Fail",
      Circle: "Circle",
    },
  },
  {
    title: "线框风格",
    icons: {
      LocationOutlined: "LocationOutlined",
      LikeOutlined: "LikeOutlined",
      StarOutlined: "StarOutlined",
      PhoneOutlined: "PhoneOutlined",
      SettingOutlined: "SettingOutlined",
      FireOutlined: "FireOutlined",
      CouponOutlined: "CouponOutlined",
      CartOutlined: "CartOutlined",
      ShoppingCartOutlined: "ShoppingCartOutlined",
      CartCircleOutlined: "CartCircleOutlined",
      FriendsOutlined: "FriendsOutlined",
      CommentOutlined: "CommentOutlined",
      GemOutlined: "GemOutlined",
      GiftOutlined: "GiftOutlined",
      PointGiftOutlined: "PointGiftOutlined",
      SendGiftOutlined: "SendGiftOutlined",
      ServiceOutlined: "ServiceOutlined",
      BagOutlined: "BagOutlined",
      TodoListOutlined: "TodoListOutlined",
      BalanceListOutlined: "BalanceListOutlined",
      Close: "Close",
      ClockOutlined: "ClockOutlined",
      QuestionOutlined: "QuestionOutlined",
      Passed: "Passed",
      AddOutlined: "AddOutlined",
      GoldCoinOutlined: "GoldCoinOutlined",
      InfoOutlined: "InfoOutlined",
      PlayCircleOutlined: "PlayCircleOutlined",
      PauseCircleOutlined: "PauseCircleOutlined",
      StopCircleOutlined: "StopCircleOutlined",
      WarningOutlined: "WarningOutlined",
      PhoneCircleOutlined: "PhoneCircleOutlined",
      MusicOutlined: "MusicOutlined",
      SmileOutlined: "SmileOutlined",
      ThumbCircleOutlined: "ThumbCircleOutlined",
      CommentCircleOutlined: "CommentCircleOutlined",
      BrowsingHistoryOutlined: "BrowsingHistoryOutlined",
      UnderwayOutlined: "UnderwayOutlined",
      MoreOutlined: "MoreOutlined",
      VideoOutlined: "VideoOutlined",
      ShopOutlined: "ShopOutlined",
      ShopCollectOutlined: "ShopCollectOutlined",
      ShareOutlined: "ShareOutlined",
      ChatOutlined: "ChatOutlined",
      SmileCommentOutlined: "SmileCommentOutlined",
      VipCardOutlined: "VipCardOutlined",
      AwardOutlined: "AwardOutlined",
      DiamondOutlined: "DiamondOutlined",
      VolumeOutlined: "VolumeOutlined",
      ClusterOutlined: "ClusterOutlined",
      WapHomeOutlined: "WapHomeOutlined",
      PhotoOutlined: "PhotoOutlined",
      GiftCardOutlined: "GiftCardOutlined",
      ExpandOutlined: "ExpandOutlined",
      MedalOutlined: "MedalOutlined",
      GoodJobOutlined: "GoodJobOutlined",
      ManagerOutlined: "ManagerOutlined",
      LabelOutlined: "LabelOutlined",
      BookmarkOutlined: "BookmarkOutlined",
      BillOutlined: "BillOutlined",
      HotOutlined: "HotOutlined",
      HotSaleOutlined: "HotSaleOutlined",
      NewOutlined: "NewOutlined",
      NewArrivalOutlined: "NewArrivalOutlined",
      GoodsCollectOutlined: "GoodsCollectOutlined",
      EyeOutlined: "EyeOutlined",
    },
  },
  {
    title: "实底风格",
    icons: {
      Location: "Location",
      Like: "Like",
      Star: "Star",
      Phone: "Phone",
      Setting: "Setting",
      Fire: "Fire",
      Coupon: "Coupon",
      Cart: "Cart",
      ShoppingCart: "ShoppingCart",
      CartCircle: "CartCircle",
      Friends: "Friends",
      Comment: "Comment",
      Gem: "Gem",
      Gift: "Gift",
      PointGift: "PointGift",
      SendGift: "SendGift",
      Service: "Service",
      Bag: "Bag",
      TodoList: "TodoList",
      BalanceList: "BalanceList",
      Clear: "Clear",
      Clock: "Clock",
      Question: "Question",
      Checked: "Checked",
      Add: "Add",
      GoldCoin: "GoldCoin",
      Info: "Info",
      PlayCircle: "PlayCircle",
      PauseCircle: "PauseCircle",
      StopCircle: "StopCircle",
      Warning: "Warning",
      PhoneCircle: "PhoneCircle",
      Music: "Music",
      Smile: "Smile",
      ThumbCircle: "ThumbCircle",
      CommentCircle: "CommentCircle",
      BrowsingHistory: "BrowsingHistory",
      Underway: "Underway",
      More: "More",
      Video: "Video",
      Shop: "Shop",
      ShopCollect: "ShopCollect",
      Share: "Share",
      Chat: "Chat",
      SmileComment: "SmileComment",
      VipCard: "VipCard",
      Award: "Award",
      Diamond: "Diamond",
      Volume: "Volume",
      Cluster: "Cluster",
      WapHome: "WapHome",
      Photo: "Photo",
      GiftCard: "GiftCard",
      Expand: "Expand",
      Medal: "Medal",
      GoodJob: "GoodJob",
      Manager: "Manager",
      Label: "Label",
      Bookmark: "Bookmark",
      Bill: "Bill",
      Hot: "Hot",
      HotSale: "HotSale",
      New: "New",
      NewArrival: "NewArrival",
      GoodsCollect: "GoodsCollect",
    },
  },
];

export const AllTaroifyIconsKey = TaroifyIcons.flatMap((item) =>
  Object.keys(item.icons)
);

export default TaroifyIcons.reduce((acc, cur) => {
  const icons = cur.icons;
  Object.keys(icons).forEach((iconName) => {
    acc[iconName] = icons[iconName];
  });
  return acc;
}, {});
