export const HarmonyIcons = [
  {
    title: "系统UI",
    icons: {
      HM_airplane_fill: "󰄓",
      HM_arrow_clockwise: "󰃇",
      HM_arrow_counterclockwise: "󰃈",
      HM_arrow_counterclockwise_clock: "󰏕",
      HM_arrow_down_right_and_arrow_up_left: "󰃉",
      HM_arrow_right_up_and_square: "󰃋",
      HM_arrow_up_left_and_arrow_down_right: "󰃍",
      HM_arrowshape_turn_up_right_fill: "󰣂",
      HM_battery: "󰄚",
      HM_battery_75percent: "󰙙",
      HM_bell_fill: "󰇑",
      HM_bell_slash: "󰇓",
      HM_bell_slash_fill: "󰇒",
      HM_bluetooth: "󰉔",
      HM_bluetooth_slash: "󰉓",
      HM_bookmark: "󰀊",
      HM_bookmark_filled_on_bookmark: "󰙚",
      HM_brush: "󰀍",
      HM_brush_fill: "󰀌",
      HM_checkmark: "󰀓",
      HM_checkmark_circle: "󰀏",
      HM_checkmark_circle_fill: "󰀎",
      HM_checkmark_square: "󰀒",
      HM_checkmark_square_fill: "󰇚",
      HM_checkmark_square_on_square: "󰀑",
      HM_checkmark_square_on_square_fill: "󰇙",
      HM_circle_viewfinder: "󰄣",
      HM_clean: "󰀖",
      HM_clean_fill: "󰀕",
      HM_dot_grid_1x2: "󰁠",
      HM_dot_grid_2x2: "󰁡",
      HM_externaldrive: "󰃟",
      HM_externaldrive_fill: "󰃞",
      HM_externaldrive_fill_3: "󰄞",
      HM_eye: "󰄠",
      HM_eye_slash: "󰄟",
      HM_flag: "󰆬",
      HM_flashlight_off_fill: "󰀚",
      HM_flashlight_on_fill: "󰀜",
      HM_full_screen_fill: "󰕊",
      HM_gearshape: "󰀠",
      HM_hand_point_up_tap_fill: "󰒄",
      HM_hand_point_up_tap_fill_1: "󰔢",
      HM_hand_point_up_tap_fill_slash: "󰙱",
      HM_hand_tap: "󰒊",
      HM_hand_thumbsup_fill: "󰗗",
      HM_heart: "󰀥",
      HM_heart_fill: "󰀡",
      HM_heart_slash: "󰀤",
      HM_house: "󰀧",
      HM_house_fill: "󰀦",
      HM_label: "󰈈",
      HM_line_viewfinder: "󰀨",
      HM_lock: "󰀈",
      HM_lock_fill: "󰓁",
      HM_lock_filled_arrow_counterclockwise: "󰕼",
      HM_lock_open: "󰓄",
      HM_lock_open_fill: "󰓃",
      HM_magnifyingglass: "󰀩",
      HM_mic: "󰀆",
      HM_mic_fill: "󰌕",
      HM_minus: "󰀬",
      HM_minus_circle: "󰀫",
      HM_minus_magnifyingglass: "󰚀",
      HM_moon_circle_fill: "󰕮",
      HM_moon_fill: "󰀭",
      HM_moon_slash_circle: "󰕯",
      HM_more: "󰕰",
      HM_nfc: "󰓗",
      HM_nfc_fill: "󰓖",
      HM_paperplane: "󰀰",
      HM_paperplane_right_fill: "󰢨",
      HM_pin: "󰀲",
      HM_pin_fill_1: "󰢫",
      HM_plus: "󰀵",
      HM_plus_magnifyingglass: "󰄧",
      HM_plus_square: "󰣃",
      HM_plus_square_on_square_fill: "󰁭",
      HM_power: "󰀶",
      HM_qrcode: "󰄨",
      HM_rays: "󰀷",
      HM_rectangle_and_arrowshape_turn_up_right: "󰃕",
      HM_rectangle_portrait_rotate: "󰀸",
      HM_rectangle_rotate: "󰢭",
      HM_redo: "󰇴",
      HM_save: "󰀻",
      HM_share: "󰀽",
      HM_slider_horizontal_2: "󰁲",
      HM_slider_vertical_3: "󰄪",
      HM_speaker: "󰁄",
      HM_speaker_slash: "󰁃",
      HM_speaker_wave_3: "󰁊",
      HM_speaker_wave_3_slash: "󰖏",
      HM_square_fill_grid_2x2: "󰁋",
      HM_square_grid_2x2: "󰃣",
      HM_star: "󰁎",
      HM_star_fill: "󰀉",
      HM_sun_max: "󰁐",
      HM_sun_max_fill: "󰁏",
      HM_sun_min: "󰁑",
      HM_trash: "󰀁",
      HM_trash_fill: "󰁒",
      HM_undo: "󰇳",
      HM_wifi: "󰀀",
      HM_wifi_slash: "󰚑",
      HM_xmark: "󰁖",
      HM_xmark_circle: "󰁕",
      HM_xmark_circle_fill: "󰁔",
    },
  },
  {
    title: "时间",
    icons: {
      HM_alarm_fill_1: "󰗯",
      HM_calendar: "󰏚",
      HM_calendar_badge_clock: "󰏘",
      HM_calendar_fill: "󰏙",
      HM_clock: "󰏝",
      HM_clock_fill: "󰏜",
      HM_stopwatch_2: "󰗰",
      HM_timer: "󰐆",
      HM_timer_circle_fill: "󰗶",
      HM_worldclock: "󰐊",
      HM_worldclock_fill: "󰐉",
      HM_worldclock_fill_2: "󰗱",
    },
  },
  {
    title: "箭头",
    icons: {
      HM_arrow_clockwise: "󰃇",
      HM_arrow_counterclockwise: "󰃈",
      HM_arrow_counterclockwise_clock: "󰏕",
      HM_arrow_down_circle: "󰢝",
      HM_arrow_down_right_and_arrow_up_left: "󰃉",
      HM_arrow_left: "󰃊",
      HM_arrow_left_circle: "󰚟",
      HM_arrow_right: "󰈱",
      HM_arrow_right_circle: "󰚠",
      HM_arrow_right_up_and_square: "󰃋",
      HM_arrow_up_circle: "󰃌",
      HM_arrow_up_circle_fill: "󰈲",
      HM_arrow_up_left: "󰈳",
      HM_arrow_up_left_and_arrow_down_right: "󰃍",
      HM_arrow_up_to_line: "󰃏",
      HM_arrowshape_3_triangle_path: "󰓵",
      HM_arrowshape_down_to_line_fill: "󰃐",
      HM_arrowshape_turn_up_right_fill: "󰣂",
      HM_arrowshape_up: "󰈽",
      HM_arrowshape_up_fill: "󰈹",
      HM_arrowshape_up_frame_fill: "󰈺",
      HM_arrowshape_up_left_and_arrowshape_down_right: "󰟮",
      HM_arrowshape_up_to_line_fill: "󰀐",
      HM_arrowtriangle_down_fill: "󰈿",
      HM_arrowtriangle_up_fill: "󰉀",
      HM_chevron_down: "󰃛",
      HM_chevron_down_2_circle: "󰛀",
      HM_chevron_down_circle: "󰛁",
      HM_chevron_left: "󰃚",
      HM_chevron_left_2: "󰛂",
      HM_chevron_left_circle: "󰛃",
      HM_chevron_right: "󰃙",
      HM_chevron_right_circle: "󰛄",
      HM_chevron_up: "󰃘",
      HM_chevron_up_2: "󰛆",
      HM_chevron_up_2_circle: "󰛅",
      HM_chevron_up_circle: "󰑟",
      HM_line_below_arrowtriangle_up_circle_fill: "󰐖",
      HM_line_below_arrowtriangle_up_fill: "󰐗",
      HM_paperplane: "󰀰",
      HM_rectangle_and_arrowshape_turn_up_right: "󰃕",
      HM_redo: "󰇴",
      HM_transfer_station: "󰞈",
      HM_undo: "󰇳",
    },
  },
  {
    title: "相机与照片",
    icons: {
      HM_arrow_down_and_rectangle_on_rectangle: "󰐝",
      HM_arrow_up_and_rectangle_on_rectangle: "󰐠",
      HM_camera: "󰑛",
      HM_camera_fill: "󰐸",
      HM_camera_filters_fill: "󰠬",
      HM_capture_smiles: "󰗈",
      HM_circle_lefthalf_inset_filled: "󰁜",
      HM_circle_righthalf_inset_filled: "󰁝",
      HM_dot_video_fill: "󰂂",
      HM_drop: "󰁣",
      HM_drop_bottomrighthalf_inset_filled: "󰄶",
      HM_flower: "󰊄",
      HM_hand_draw: "󰁦",
      HM_heart_square_stack_fill: "󰔔",
      HM_lightbulb: "󰊜",
      HM_lightbulb_slash: "󰊚",
      HM_line_arrowtriangle_2_inward: "󰁨",
      HM_livephoto: "󰗷",
      HM_movie_fill: "󰓒",
      HM_paintpalette: "󰄥",
      HM_picture: "󰀃",
      HM_picture_2: "󰓥",
      HM_picture_damage: "󰓩",
      HM_picture_fill: "󰓪",
      HM_play_video: "󰓮",
      HM_play_video_fill: "󰢬",
      HM_puzzle: "󰒠",
      HM_puzzle_fill: "󰒵",
      HM_rectangle_on_rectangle: "󰒢",
      HM_rectangle_on_rectangle_fill: "󰒡",
      HM_resolution_video: "󰒣",
      HM_scope: "󰒦",
      HM_scope_slash: "󰒥",
      HM_shutter_photo: "󰒯",
      HM_square_slash: "󰒴",
      HM_template: "󰓿",
      HM_template_fill: "󰓾",
      HM_video_fill: "󰂣",
      HM_video_slasj_fill: "󰡁",
      HM_xmark_picture: "󰡂",
      HM_xmark_picture_fill: "󰠡",
    },
  },
  {
    title: "办公文件",
    icons: {
      HM_arrow_right_folder_circle: "󰂺",
      HM_arrow_right_folder_fill: "󰂻",
      HM_book_open_fill: "󰟉",
      HM_book_pages_fill_1: "󰢿",
      HM_briefcase: "󰙟",
      HM_case_fill: "󰙠",
      HM_checkmark_clipboard_fill: "󰆊",
      HM_doc: "󰂽",
      HM_doc_plaintext: "󰃁",
      HM_doc_plaintext_and_pencil: "󰖯",
      HM_doc_plaintext_and_pencil_fill: "󰙩",
      HM_doc_plaintext_fill: "󰃂",
      HM_doc_text: "󰂼",
      HM_doc_text_badge_arrow_up: "󰖱",
      HM_doc_text_badge_checkmark: "󰃄",
      HM_doc_text_badge_magnifyingglass: "󰖳",
      HM_doc_text_fill: "󰂿",
      HM_folder: "󰃅",
      HM_folder_badge_eye: "󰖽",
      HM_folder_badge_plus: "󰀄",
      HM_folder_fill: "󰃆",
      HM_form: "󰆔",
      HM_grid: "󰙰",
      HM_list_square_bill: "󰖿",
      HM_paperclip: "󰄏",
      HM_text_clipboard: "󰆝",
    },
  },
  {
    title: "键盘",
    icons: {
      HM_asterisk_rectangle_badge_handwritten: "󰋮",
      HM_celiakeyboard_elevate: "󰒒",
      HM_celiakeyboard_mechanical: "󰋲",
      HM_celiakeyboard_menu_icon_size: "󰋳",
      HM_delete_left: "󰃝",
      HM_delete_left_fill: "󰕁",
      HM_input_mode: "󰒔",
      HM_keyboard_badge_bihua: "󰌂",
      HM_keyboard_badge_cangjie: "󰌃",
      HM_keyboard_badge_handwritten: "󰌆",
      HM_keyboard_badge_spell: "󰌇",
      HM_keyboard_badge_wubi: "󰌈",
      HM_keyboard_badge_zhuyin: "󰌉",
      HM_keyboard_circle: "󰅲",
      HM_keyboard_onehanded_left: "󰌌",
      HM_keyboard_onehanded_right: "󰌍",
      HM_keyboard_square: "󰌎",
      HM_keyboard_thumbmode: "󰌏",
      HM_onehand: "󰌘",
      HM_selector: "󰌛",
      HM_space_1: "󰌜",
      HM_swipeup_input: "󰌞",
      HM_traditional_square: "󰌢",
      HM_translate: "󰁾",
      HM_translate_c2e: "󰌣",
      HM_translate_e2c: "󰌤",
    },
  },
  {
    title: "媒体",
    icons: {
      HM_backward_end_fill: "󰂦",
      HM_discover_fill: "󰇛",
      HM_fast_forward: "󰙫",
      HM_forward_end_fill: "󰂧",
      HM_gobackward_15: "󰏲",
      HM_gobackward_30: "󰏳",
      HM_goforward_10: "󰏴",
      HM_goforward_15: "󰏵",
      HM_goforward_30: "󰏶",
      HM_headphones_fill: "󰙲",
      HM_identify_song: "󰌻",
      HM_list_interrupt: "󰌼",
      HM_media_center: "󰙼",
      HM_music: "󰂭",
      HM_music_fill: "󰂪",
      HM_music_note_list: "󰂬",
      HM_order_play: "󰂮",
      HM_pause: "󰂱",
      HM_pause_round_triangle_fill: "󰡫",
      HM_play_circle_fill: "󰂲",
      HM_play_fill: "󰂴",
      HM_play_hexagon_fill: "󰠓",
      HM_play_round_rectangle_fill: "󰠔",
      HM_record_circle: "󰂷",
      HM_remove_songlist: "󰍣",
      HM_repeat: "󰂸",
      HM_repeat_1: "󰂹",
      HM_reverse_order: "󰏽",
      HM_service: "󰍥",
      HM_shuffle: "󰂵",
      HM_skip_silence: "󰎻",
    },
  },
  {
    title: "通信",
    icons: {
      HM_beidou_satellite_circle_fill: "󰔖",
      HM_beidou_satellite_fill: "󰚭",
      HM_dial: "󰂁",
      HM_ellipsis_bubble: "󰑳",
      HM_ellipsis_message: "󰂅",
      HM_ellipsis_message_fill: "󰂄",
      HM_envelope: "󰂈",
      HM_envelope_fill: "󰂉",
      HM_envelope_open_fill: "󰂊",
      HM_hd_square_fill: "󰊊",
      HM_message: "󰂏",
      HM_message_badge_gearshape_1: "󰝖",
      HM_message_on_message: "󰂎",
      HM_message_on_message_fill: "󰂍",
      HM_mic: "󰀆",
      HM_mic_circle: "󰌔",
      HM_mic_fill: "󰌕",
      HM_mic_slash: "󰝘",
      HM_mic_slash_fill: "󰌗",
      HM_phone_down_fill: "󰂟",
      HM_phone_fill: "󰂞",
      HM_recordingtape: "󰅶",
      HM_recordingtape_rectangle: "󰅵",
      HM_recordingtape_rectangle_fill: "󰅴",
      HM_satellite: "󰅷",
    },
  },
  {
    title: "连接",
    icons: {
      HM_bluetooth: "󰉔",
      HM_bluetooth_slash: "󰉓",
      HM_dot_radiowaves_left_and_right: "󰉹",
      HM_hotspot: "󰊏",
      HM_icloud: "󰊔",
      HM_icloud_slash: "󰊓",
      HM_icloud_slash_fill: "󰊒",
      HM_link_slash: "󰊠",
      HM_mobiledata: "󰊩",
      HM_nfc: "󰓗",
      HM_nfc_fill: "󰓖",
      HM_wifi: "󰀀",
      HM_wifi_slash: "󰚑",
    },
  },
  {
    title: "符号标识",
    icons: {
      HM_bolt: "󰉢",
      HM_bolt_filled_on_circle: "󰉟",
      HM_bolt_shield_fill: "󰟱",
      HM_exclamationmark: "󰄋",
      HM_exclamationmark_circle: "󰄉",
      HM_exclamationmark_shield_fill: "󰑷",
      HM_exclamationmark_triangle_fill: "󰛗",
      HM_info_circle: "󰊖",
      HM_info_shield: "󰊗",
      HM_nosign: "󰄎",
      HM_questionmark_circle: "󰄀",
    },
  },
  {
    title: "编辑",
    icons: {
      HM_calculator_1: "󰡟",
      HM_character_arrow_clockwise: "󰇖",
      HM_character_viewfinder: "󰇘",
      HM_circle_dashed: "󰄴",
      HM_close_sidebar: "󰢟",
      HM_crop_rotate: "󰅡",
      HM_cut: "󰁟",
      HM_eraser_line: "󰁥",
      HM_indent_right: "󰅣",
      HM_indentation_left: "󰅤",
      HM_list_bullet: "󰁩",
      HM_list_bullet_circle: "󰅦",
      HM_list_bullet_square_fill: "󰅧",
      HM_list_checkmask: "󰅂",
      HM_list_letter: "󰅄",
      HM_list_number: "󰅃",
      HM_list_square: "󰅅",
      HM_open_sidebar: "󰢧",
      HM_paintbrush: "󰟞",
      HM_paintbrush_fill: "󰟝",
      HM_paintpalette_fill: "󰄤",
      HM_pencil_line_1: "󰘦",
      HM_pencil_waveform: "󰁬",
      HM_pencil_waveform_fill: "󰘧",
      HM_rectangle_and_cut: "󰁯",
      HM_rename: "󰁱",
      HM_sort: "󰖁",
      HM_square_and_pencil: "󰁳",
      HM_square_and_pencil_fill: "󰁴",
      HM_swap: "󰋑",
      HM_text_aligncenter: "󰁶",
      HM_text_alignleft: "󰁷",
      HM_text_alignright: "󰁸",
      HM_text_and_arrow_down: "󰁹",
      HM_text_and_arrow_up: "󰁺",
      HM_textformat_size_square: "󰁼",
      HM_transparency_lock: "󰘹",
      HM_trapezoid_and_line_horizontal: "󰅪",
      HM_trapezoid_and_line_vertical: "󰅫",
      HM_triangleshape_fill: "󰍫",
      HM_vertical_flip: "󰘻",
    },
  },
  {
    title: "隐私&安全",
    icons: {
      HM_checkmark_shield: "󰑞",
      HM_checkmark_shield_fill: "󰑝",
      HM_eye: "󰄠",
      HM_eye_slash: "󰄟",
      HM_hand_raised_hexagon: "󰝃",
      HM_hand_raised_hexagon_fill: "󰒇",
      HM_key_horizontal: "󰒛",
      HM_key_shield: "󰒞",
      HM_key_shield_fill: "󰒝",
      HM_lock: "󰀈",
      HM_lock_fill: "󰓁",
      HM_lock_open: "󰓄",
      HM_lock_open_fill: "󰓃",
      HM_nearlink: "󰝜",
      HM_person_shield: "󰓞",
      HM_person_shield_fill: "󰓝",
      HM_staroflife_rectangle: "󰓸",
      HM_touchid: "󰔇",
      HM_vpn_key: "󰞏",
    },
  },
  {
    title: "人物",
    icons: {
      HM_children: "󰙣",
      HM_ear: "󰗉",
      HM_face: "󰗊",
      HM_face_smiling: "󰗐",
      HM_figure_arms_open: "󰗑",
      HM_figure_running: "󰟕",
      HM_hand_point_up_tap_fill: "󰒄",
      HM_hand_point_up_tap_fill_1: "󰔢",
      HM_hand_point_up_tap_fill_slash: "󰙱",
      HM_hand_tap: "󰒊",
      HM_person: "󰗥",
      HM_person_2: "󰗜",
      HM_person_2_fill: "󰗛",
      HM_person_badge_plus: "󰗟",
      HM_person_crop_circle_fill_1: "󰗳",
      HM_person_filled_badge_plus: "󰗤",
      HM_person_filled_viewfinder: "󰕹",
      HM_person_square_fill: "󰕺",
      HM_portrait: "󰗇",
    },
  },
  {
    title: "形状",
    icons: {
      HM_circle: "󰀇",
      HM_oval: "󰍋",
      HM_rectangle: "󰁰",
      HM_rectangle_split_3x1: "󰔨",
      HM_rotate_left: "󰍤",
      HM_smallcircle_filled_circle: "󰅩",
      HM_square: "󰁵",
    },
  },
  {
    title: "交通出行",
    icons: {
      HM_local_fill: "󰆸",
      HM_location_north_up_right_circle_fill: "󰠍",
      HM_map: "󰇂",
      HM_map_badge_local: "󰇀",
      HM_map_slash: "󰇃",
      HM_navigation: "󰠐",
      HM_position: "󰇊",
      HM_route_plan: "󰟤",
      HM_satellite_map: "󰝵",
      HM_satellite_map_fill: "󰝴",
    },
  },
];

export const AllHarmonyIconsKey = HarmonyIcons.flatMap((item) =>
  Object.keys(item.icons)
);

export default HarmonyIcons.reduce((acc, cur) => {
  const icons = cur.icons;
  Object.keys(icons).forEach((iconName) => {
    acc[iconName] = icons[iconName];
  });
  return acc;
}, {});
